version: '3.7'

services:
  nest-backend:
    image: nest-api
    container_name: nest-app
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=production
      - API_PORT=5000
      - API_ACCESS_TOKEN_SECRET=mksBackendChallenge
      - API_ACCESS_TOKEN_TTL_IN_HOURS=2
      - API_LOG_ENABLE=true
      - API_LOG_LEVEL=log
      - DB_URL=postgres://mtjraesczpjwfz:8a341214ff8eb6d8e50ffed43966caf16106c88fafde626dfa9ce2e8ab1465cd@ec2-44-215-176-210.compute-1.amazonaws.com:5432/d73lj2a3f7v0ud
      - DB_LOG_ENABLE=false
      - DB_SYNC=false
      - REDIS_URL=rediss://:p3c87b84481b891b1a949cf70c2952e3a48441fde5b910b3956e3e73f8c7f3f58@ec2-52-5-21-177.compute-1.amazonaws.com:17120
    restart: unless-stopped
